print("goa")
print("world")
print("saqartvelo")
print(30)
print("Tbilisi")
print('england')
print("never give up")
print("football")
print ("barcelona")
print("hard work")
print(24)
print(2026)
print("success")
print("love")
print("family")
print("school")
print("room")
print("anything")
print("people")
print("davit shavidzes razmi is the best")
print(2026)
print(1)